### ISSUE TITLE
Bazar: How to improve filters: by region/country ? 

### ISSUE THREAD

**Issue by tx4x** [hakkens/precious-plastic#85]
Hi,
do you have some pointers about how to introduce more filters: region/country?  It's really tedious to get through the items, just to check it's on a certain continent since the shipping are fees more likely a show breaker. 

I was searching around how to contribute but I failed to get a development setup up & running. Could you add some more contribution guide ? 
I am not sure where or how to start.
Thanks,
kind regards,
guenter

**Comment by davehakkens** [comment]
currently the bazar runs on [sharetribe](https://www.sharetribe.com/), external platform to text/run our beta version quickly. But very limited in customisation.. In the future we want to develop our own and we will be more flexible..

**Comment by tx4x** [comment]
right, will checkout it anyways, thanks for now!

**Comment by tx4x** [comment]
So I did check 'sharetribe', indeed, very limited. It's actally a trivial application and I could help with building the first prototype with React and Typescript (my personal favourite to build web-apps). All I need is the map marker data and I'm ready to go. To impl. the selling feature, there are wordpress plugins, though. Do you have already ideas about ? If not, I can write a proposal. Would be nice to have a 'meta' repository for the precious plastic project; something where we could store such ideas, guides, etc... 
g

**Comment by davehakkens** [comment]
Cool! Haven't really thought about it yet. Very open for proposals though!

**Comment by nzchicken** [comment]
@tx4x I'm happy to help out with a React build. I've been meaning to learn Typescript for some time, so it's a good use case. I helped Dave out with building the maps, so can give you some guidance on how the pins work.

**Comment by davehakkens** [comment]
Not sure if this is useful in any way or as a starting point but you can download sharetribe source code from github https://github.com/sharetribe/sharetribe

**Comment by tx4x** [comment]
that helps! let me check, being quite busy right now with new machinery :-) back to you in a couple of days,
thanks for the heads up

**Comment by tx4x** [comment]
@davehakkens it seems easy to extend, i am now just worried to host a custom version. i can do that for free but i've to maintain a fork as well. not sure the benefits out weight the efforts.  

otherwise, i can go back to square one and write a proposal. i always prefer inhouse but we have to ensure it can be maintained without me. eventually we leave it as it is but we open a request to sharetribe!?

**Comment by davehakkens** [comment]
square one! We are long term thinkers and our own platform is a crucial element for that :)

**Comment by tx4x** [comment]
ok :-)
I will do this proposal/design til next monday; after that I can start coding since i have a little more time. See you soon, 
kind regards,
guenter

**Comment by tx4x** [comment]
I opened a dedicated repository for meta/design/template stuff [here](https://github.com/tx4x/precious-plastic-meta). Eventually you take it over sometime... There will be as next a POC (prove of concept) for the bazar, after we agreed on some points.

**Comment by tx4x** [comment]
I never tested this but there is an Ebay API to create items! That could resolve a LOT of issues and problems, handling the overhead of user items should be almost the same than coding/maintaining a shopping portal. Just thinking loud :-)
g

**Comment by tx4x** [comment]
most home machine guys i know don't run a web-site, they only have an ebay store.

here the pros:
- international exposure of recycled plastic (stock, products) , for free!
- handling of international shipping, billing, payments and refunds
- the whole interface/ui is there already
- PP becomes an credible plastic resource, faster than any other way i can imagine 
- finally international filtering, with some 'tricks' like multiple sellers 

since it's all accessible via API, we can still render the items via API the more fancy/PP way :-)
g

**Comment by davehakkens** [comment]
Sounds cool! But in the future we also want to focus more on the plastic objects created by the community. We want to display them beautiful and deliver a proper a clean user experience. Ebay isn't really that..

**Comment by tx4x** [comment]
Ok, we can still compile nice nightly build 'interfaces' fresh from Ebay, on the fly. To me, if it comes to shopping and building products, i won't be really interested in a custom shop interface. For that precious plastic is still too pro stuff anyways though; The idea is rather to build an elegant app around Ebay, just the whole shopping thing is solved :-) At the end it's just an adapter, not a monster as sharetribe

**Comment by nzchicken** [comment]
@tx4x for some context, from the conversations I've had with Dave in the past, I think the general idea around precious plastic (even hakkens related stuff in general) is to try and keep it as opensource as possible, and to support opensource where possible. For things like hosting, options get limited, but coming to e-commerce, there's other options. So although dave ends up paying for ShareTribe, and the fact that they're offering their code as open source is important.

So add on top of that, Dave being a designer and all, that look and feel is important and making it easy for people to find and get what they want whilst spreading the message is important. So that's the challenge to us a developers I guess. Go hard on the open source where we can, try and get that UI/UX as accessible and consistent as possible, and make it as easy as it can be to help people use plastic in a better way.

@davehakkens is that a good summary?

**Comment by davehakkens** [comment]
nailed it @nzchicken

**Comment by tx4x** [comment]
@nzchicken well, that's one of the stubborn reasons why I left the precious plastic project, at least for now. If you put this fancy requirements like open-source and utterly useless interface of sharetribe above actual outcome & success of the project, then to me the project is rather condemned to fail (just look at the sharetribe sales). It's like talking to hopeless hippies (i've spoken to hundreds in the last decade...) who never understand that success & money needs to be secured first. you need cash flow to finance good projects. 

good luck fellows, you may realize one day that bazar is the worst bottleneck right now. everyone is sitting on their plastic and no one knows about. you also seem to ignore that your users are no grannies which may prefer sharetribe like interface over eBay. most of the users are pretty much confident with eBay, I can't think even remotely how one would prefer another shopping experience in this field.

**Comment by tx4x** [comment]
one thing you obviously don't want to realize or see: 
the reason why precious plastic exists is because of inefficient recycling by the industry and general waste attitude of the population. now coming up with some fancy website, somewhere hidden in the web and no one knows about is plain stupid! Dave, I hope you wake up sometime and start realizing what you actually did to you and the others (responsibilities...) by leading us here... you lock up your community behind fences for childish and absurd reasons,... you remember the slap ? you should get one just for this :-)

it's about efficiency, to save as much plastic as we can, so just make sure it can grow as it needs and deserves. there wasn't a single convincing argument to go with 'open source',...it's just a luxurity you cant effort if you want to succeed. period

**Comment by davehakkens** [comment]
We’ve come a long way with very limited resources and believe we can do
much more following our approuch
Obviously people have different strategies and paths to get somewhere. No
clue if our way is right.
To only thing I can assure is we keep moving forward towards our goal.
You decide yourself to hop on or which lead to follow @tx4x




On 7 June 2018 at 19:27:11, tx4x (notifications@github.com) wrote:

one thing you obviously don't want to realize or see:
the reason why precious plastic exists is because of inefficient recycling
by the industry and general waste attitude of the population. now coming up
with some fancy website, somewhere hidden in the web and no one knows about
is plain stupid! Dave, I hope you wake up sometime and start realizing what
you actually did to you and the others (responsibilities...) by leading us
here... you lock up your community behind fences for childish and absurd
reasons,... you remember the slap ? you should get one just for this :-)

it's about efficiency, to save as much plastic as we can, so just make sure
it can grow as it needs and deserves. there wasn't a single convincing
argument to go with 'open source',...it's just a luxurity you cant effort
if you want to succeed. period

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/hakkens/precious-plastic/issues/85#issuecomment-395501296>,
or mute the thread
